ALTER TABLE `t_item` DROP `link`;
ALTER TABLE `t_item` DROP `appendWords`;
ALTER TABLE `t_item` DROP `priceHKD`;
ALTER TABLE `t_order` ADD  `addtionalGreetings` VARCHAR( 500 ) NOT NULL;
ALTER TABLE  `t_inventory` ADD  `inventoryId` INT( 32 ) NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;
update `t_inventory` set inventoryId = -inventoryId;

INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-1,'100','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-1,'84','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-2,'101','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-2,'84.84','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-3,'102','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-3,'85.68','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-4,'103','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-4,'86.52','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-5,'104','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-5,'87.36','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-6,'105','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-6,'88.2','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-7,'106','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-7,'89.04','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-8,'107','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-8,'89.88','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-9,'108','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-9,'90.72','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-10,'109','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-10,'91.56','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-11,'110','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-11,'92.4','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-12,'111','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-12,'93.24','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-13,'112','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-13,'94.08','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-14,'113','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-14,'94.92','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-15,'114','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-15,'95.76','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-16,'115','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-16,'96.6','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-17,'116','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-17,'97.44','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-18,'117','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-18,'98.28','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-19,'118','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-19,'99.12','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-20,'119','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-20,'99.96','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-21,'120','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-21,'100.8','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-22,'121','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-22,'101.64','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-23,'122','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-23,'102.48','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-24,'123','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-24,'103.32','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-25,'124','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-25,'104.16','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-26,'125','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-26,'105','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-27,'126','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-27,'105.84','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-28,'127','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-28,'106.68','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-29,'128','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-29,'107.52','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-30,'129','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-30,'108.36','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-31,'130','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-31,'109.2','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-32,'131','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-32,'110.04','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-33,'132','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-33,'110.88','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-34,'133','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-34,'111.72','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-35,'134','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-35,'112.56','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-36,'135','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-36,'113.4','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-37,'136','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-37,'114.24','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-38,'137','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-38,'115.08','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-39,'138','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-39,'115.92','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-40,'139','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-40,'116.76','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-41,'140','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-41,'117.6','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-42,'141','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-42,'118.44','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-43,'142','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-43,'119.28','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-44,'143','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-44,'120.12','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-45,'144','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-45,'120.96','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-46,'145','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-46,'121.8','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-47,'146','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-47,'122.64','HKD');
INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-48,'147','CNY');	INSERT INTO `t_itemprice`(`itemId`, `price`, `currency`) VALUES (-48,'123.48','HKD');
